url: https://renewedtab.com
description: A customisable New Tab page, with widgets and beautiful backgrounds
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-redirect-from

exclude:
  - locale
  - util

firefox: https://addons.mozilla.org/addon/renewed-tab/?utm_source=renewedtab.com&utm_medium=referral
chrome: https://chrome.google.com/webstore/detail/renewed-tab/laljofodhebajcajogbolahbjdcnfgkf?utm_source=renewedtab.com&utm_medium=referral

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/

future: true
