# url: https://localhost.rubenwardy.com
description: A customisable New Tab page, with widgets and beautiful backgrounds
permalink: pretty
sass:
  style: compressed

plugins:
  - jekyll-redirect-from

firefox: https://addons.mozilla.org/addon/renewed-tab/?utm_source=renewedtab.rubenwardy.com&utm_medium=referral
chrome: https://chrome.google.com/webstore/detail/renewed-tab/laljofodhebajcajogbolahbjdcnfgkf?utm_source=renewedtab.rubenwardy.com&utm_medium=referral
